name: Build and Push Docker Images
 
on:
  push:
    branches: [ main ]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        include:
          - service: java-app
            path: services/java-app
            file: Dockerfile
          - service: node-app
            path: services/node-app
            file: Dockerfile
          - service: python-app
            path: services/python-app
            file: Dockerfile
 
    steps:
      #  Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4
 
      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      #  Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      #  Cache language dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/.m2/repository
            **/node_modules
            **/venv
          key: ${{ runner.os }}-deps-${{ matrix.service }}-${{ hashFiles(matrix.path + '/**') }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ matrix.service }}-
 
      #  Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.path }}/${{ matrix.file }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.service }}:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.service }}:cache,mode=max
